// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvL78SzuO_fF4pcvgnrW4OWE0_kr51API',
    appId: '1:509983480520:web:a036636437b539ec1b63fd',
    messagingSenderId: '509983480520',
    projectId: 'plataforma-bravo-7e970',
    authDomain: 'plataforma-bravo-7e970.firebaseapp.com',
    storageBucket: 'plataforma-bravo-7e970.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvL78SzuO_fF4pcvgnrW4OWE0_kr51API',
    appId: '1:509983480520:android:a036636437b539ec1b63fd',
    messagingSenderId: '509983480520',
    projectId: 'plataforma-bravo-7e970',
    authDomain: 'plataforma-bravo-7e970.firebaseapp.com',
    storageBucket: 'plataforma-bravo-7e970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvL78SzuO_fF4pcvgnrW4OWE0_kr51API',
    appId: '1:509983480520:ios:a036636437b539ec1b63fd',
    messagingSenderId: '509983480520',
    projectId: 'plataforma-bravo-7e970',
    authDomain: 'plataforma-bravo-7e970.firebaseapp.com',
    storageBucket: 'plataforma-bravo-7e970.firebasestorage.app',
    iosBundleId: 'com.example.gestaocbmgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvL78SzuO_fF4pcvgnrW4OWE0_kr51API',
    appId: '1:509983480520:macos:a036636437b539ec1b63fd',
    messagingSenderId: '509983480520',
    projectId: 'plataforma-bravo-7e970',
    authDomain: 'plataforma-bravo-7e970.firebaseapp.com',
    storageBucket: 'plataforma-bravo-7e970.firebasestorage.app',
    iosBundleId: 'com.example.gestaocbmgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvL78SzuO_fF4pcvgnrW4OWE0_kr51API',
    appId: '1:509983480520:web:a036636437b539ec1b63fd',
    messagingSenderId: '509983480520',
    projectId: 'plataforma-bravo-7e970',
    authDomain: 'plataforma-bravo-7e970.firebaseapp.com',
    storageBucket: 'plataforma-bravo-7e970.firebasestorage.app',
  );
}